# Generated by Django 3.1 on 2021-03-26 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracks',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
